CREATE TABLE [dbo].[AdvanceBooking] (
    [id]                   INT             IDENTITY (1, 1) NOT NULL,
    [BookingCode]          NVARCHAR (50)   NULL,
    [CustomerCode]         NVARCHAR (50)   NULL,
    [DateOfReservation]    DATETIME        NULL,
    [TimeOfReservtion]     DATETIME        NULL,
    [NoOfPersons]          NVARCHAR (50)   NULL,
    [SittingLocation]      NVARCHAR (100)  NULL,
    [AdvancePayment]       DECIMAL (18, 2) CONSTRAINT [DF_AdvanceBooking_AdvancePayment] DEFAULT ((0)) NULL,
    [Comments]             NVARCHAR (MAX)  NULL,
    [Smooking-NonSmooking] NVARCHAR (50)   NULL,
    [Event]                NVARCHAR (50)   NULL,
    [OrderDate]            DATETIME        NULL,
    [OrderTime]            DATETIME        NULL,
    [Order_Key]            INT             CONSTRAINT [DF_AdvanceBooking_Order_Key] DEFAULT ((0)) NULL,
    [GrossAmount]          DECIMAL (18, 2) CONSTRAINT [DF_AdvanceBooking_GrossAmount] DEFAULT ((0)) NULL,
    [Tax]                  DECIMAL (18, 2) CONSTRAINT [DF_AdvanceBooking_Tax] DEFAULT ((0)) NULL,
    [TaxType]              NVARCHAR (50)   NULL,
    [Discount]             DECIMAL (18, 2) CONSTRAINT [DF_AdvanceBooking_Discount] DEFAULT ((0)) NULL,
    [NetAmount]            DECIMAL (18, 2) CONSTRAINT [DF_AdvanceBooking_NetAmount] DEFAULT ((0)) NULL,
    [OrderStatus]          NVARCHAR (50)   NULL,
    [Tiltid]               INT             DEFAULT ((0)) NOT NULL,
    [CounterId]            INT             DEFAULT ((0)) NOT NULL,
    [ShiftNo]              NVARCHAR (50)   NULL,
    [LunchOrDinner]        NVARCHAR (50)   NULL,
    [is_upload]            BIT             DEFAULT ((0)) NOT NULL,
    [is_update]            BIT             DEFAULT ((0)) NOT NULL,
    [Item_Total]           DECIMAL (18, 2) DEFAULT ((0)) NOT NULL,
    [Item_Disocunt]        DECIMAL (18, 2) DEFAULT ((0)) NOT NULL,
    [Item_Net]             DECIMAL (18, 2) DEFAULT ((0)) NOT NULL
);

