CREATE TABLE [dbo].[BuffetBooking] (
    [id]                   INT             IDENTITY (1, 1) NOT NULL,
    [BookingCode]          NVARCHAR (50)   NULL,
    [CustomerCode]         NVARCHAR (50)   NULL,
    [DateOfReservation]    DATETIME        NULL,
    [TimeOfReservtion]     DATETIME        NULL,
    [NoOfPersons]          NVARCHAR (50)   NULL,
    [SittingLocation]      NVARCHAR (100)  NULL,
    [AdvancePayment]       DECIMAL (18, 2) CONSTRAINT [DF_BuffetBooking_AdvancePayment] DEFAULT ((0)) NULL,
    [Comments]             NVARCHAR (MAX)  NULL,
    [Smooking-NonSmooking] NVARCHAR (50)   NULL,
    [Event]                NVARCHAR (50)   NULL,
    [OrderDate]            DATETIME        NULL,
    [OrderTime]            DATETIME        NULL,
    [Order_Key]            NVARCHAR (50)   CONSTRAINT [DF_BuffetBooking_Order_Key] DEFAULT ((0)) NULL,
    [GrossAmount]          DECIMAL (18, 2) CONSTRAINT [DF_BuffetBooking_GrossAmount] DEFAULT ((0)) NULL,
    [Tax]                  DECIMAL (18, 2) CONSTRAINT [DF_BuffetBooking_Tax] DEFAULT ((0)) NULL,
    [TaxType]              NVARCHAR (50)   NULL,
    [Discount]             DECIMAL (18, 2) CONSTRAINT [DF_BuffetBooking_Discount] DEFAULT ((0)) NULL,
    [NetAmount]            DECIMAL (18, 2) CONSTRAINT [DF_BuffetBooking_NetAmount] DEFAULT ((0)) NULL,
    [IsDelete]             BIT             CONSTRAINT [DF_BuffetBooking_IsDelete] DEFAULT ((0)) NULL,
    [service_status]       NVARCHAR (50)   NULL,
    [OrderNo]              INT             NULL,
    [ServiceChaerges]      DECIMAL (18)    CONSTRAINT [DF__BuffetBoo__Servi__45DF2291] DEFAULT ((0)) NOT NULL,
    [Tip]                  DECIMAL (18)    CONSTRAINT [DF__BuffetBooki__Tip__46D346CA] DEFAULT ((0)) NOT NULL,
    [ShiftNo]              NVARCHAR (50)   NULL,
    [TiltId]               INT             CONSTRAINT [DF__BuffetBoo__TiltI__47C76B03] DEFAULT ((0)) NULL,
    [CounterId]            INT             CONSTRAINT [DF__BuffetBoo__Count__48BB8F3C] DEFAULT ((0)) NULL
);

