CREATE TABLE [dbo].[Dine_In_Order] (
    [id]                      INT             IDENTITY (840, 1) NOT NULL,
    [order_key]               NVARCHAR (50)   NULL,
    [z_number]                NVARCHAR (50)   NULL,
    [order_type]              NVARCHAR (50)   NULL,
    [order_no]                INT             NULL,
    [order_date]              DATETIME        NULL,
    [day]                     NVARCHAR (50)   NULL,
    [table_no]                NVARCHAR (50)   NULL,
    [waiter_name]             NVARCHAR (50)   NULL,
    [order_time]              NVARCHAR (50)   NULL,
    [service_time]            NVARCHAR (50)   NULL,
    [service_status]          NVARCHAR (50)   NULL,
    [account_status]          NVARCHAR (50)   NULL,
    [amount]                  FLOAT (53)      NULL,
    [DiscountType]            NVARCHAR (50)   NULL,
    [discount]                DECIMAL (18, 2) CONSTRAINT [DF_Dine_In_Order_discount] DEFAULT ((0)) NULL,
    [is_delete]               BIT             CONSTRAINT [DF_Dine_In_Order_is_delete] DEFAULT ((0)) NULL,
    [cover]                   DECIMAL (18)    CONSTRAINT [DF_TestTable_cover] DEFAULT ('0') NOT NULL,
    [estimated_time]          NVARCHAR (50)   NULL,
    [table_time]              NVARCHAR (50)   NULL,
    [kitchen_status]          BIT             CONSTRAINT [DF_Dine_In_Order_kitchen_status] DEFAULT ((0)) NOT NULL,
    [Tiltid]                  INT             NULL,
    [CounterId]               INT             NULL,
    [IsBill]                  BIT             CONSTRAINT [DF_Dine_In_Order_IsBill] DEFAULT ((0)) NULL,
    [CareOff]                 NVARCHAR (100)  NULL,
    [IsSelect]                BIT             CONSTRAINT [DF_Dine_In_Order_IsSelect] DEFAULT ((0)) NULL,
    [Customer]                NVARCHAR (MAX)  NULL,
    [Tele]                    NVARCHAR (50)   NULL,
    [ExtraCharges]            DECIMAL (18, 2) CONSTRAINT [DF_Dine_In_Order_ExtraCharges] DEFAULT ((0)) NULL,
    [DeleteReason]            NVARCHAR (MAX)  NULL,
    [UserPunch]               NVARCHAR (MAX)  NULL,
    [UserCash]                NVARCHAR (MAX)  NULL,
    [UserDelete]              NVARCHAR (MAX)  NULL,
    [KOT]                     INT             CONSTRAINT [DF_Dine_In_Order_KOT] DEFAULT ((0)) NULL,
    [tableStatus]             BIT             CONSTRAINT [DF_Dine_In_Order_tableStatus] DEFAULT ((0)) NULL,
    [OrderTiltId]             INT             CONSTRAINT [DF_Dine_In_Order_OrderTiltId] DEFAULT ((0)) NULL,
    [TimeIn]                  DATETIME        NULL,
    [TimeOut]                 DATETIME        NULL,
    [Status]                  BIT             CONSTRAINT [DF__Dine_In_O__Statu__0B3D7FB0] DEFAULT ((0)) NOT NULL,
    [Od]                      INT             CONSTRAINT [DF__Dine_In_Orde__Od__0C31A3E9] DEFAULT ((0)) NOT NULL,
    [Itemqty]                 FLOAT (53)      CONSTRAINT [DF__Dine_In_O__Itemq__0D25C822] DEFAULT ((0)) NOT NULL,
    [Itemprice]               FLOAT (53)      CONSTRAINT [DF__Dine_In_O__Itemp__0E19EC5B] DEFAULT ((0)) NOT NULL,
    [OrderKey_Merege]         NVARCHAR (50)   NULL,
    [DispatchTime]            NVARCHAR (50)   NULL,
    [OrderStatus]             NVARCHAR (50)   NULL,
    [PaymentMode]             NVARCHAR (50)   NULL,
    [isFeedback]              BIT             CONSTRAINT [DF__Dine_In_O__isFee__2E1CA799] DEFAULT ((0)) NOT NULL,
    [Feedback]                NVARCHAR (MAX)  NULL,
    [isFeedbackDone]          BIT             CONSTRAINT [DF__Dine_In_O__isFee__2F10CBD2] DEFAULT ((0)) NOT NULL,
    [IsServiceCharges]        BIT             CONSTRAINT [DF__Dine_In_O__IsSer__54425081] DEFAULT ((0)) NOT NULL,
    [ServiceCharges]          DECIMAL (18, 2) CONSTRAINT [DF__Dine_In_O__Servi__553674BA] DEFAULT ((0)) NOT NULL,
    [TabUserPunch]            NVARCHAR (50)   NULL,
    [is_upload]               BIT             CONSTRAINT [DF__Dine_In_O__is_up__076DBA23] DEFAULT ((0)) NOT NULL,
    [is_update]               BIT             CONSTRAINT [DF__Dine_In_O__is_up__0861DE5C] DEFAULT ((0)) NOT NULL,
    [Date]                    DATETIME        NULL,
    [DeleteOrderStatus]       BIT             CONSTRAINT [DF__Dine_In_O__Delet__54AD302C] DEFAULT ((0)) NOT NULL,
    [DiscountId]              NVARCHAR (50)   NULL,
    [Rider_Commision]         DECIMAL (18, 2) DEFAULT ((0)) NOT NULL,
    [Rider_IsPercent]         BIT             DEFAULT ((0)) NOT NULL,
    [Rider_Commision_Percent] DECIMAL (18, 2) DEFAULT ((0)) NOT NULL,
    [CommentsForRider]        NVARCHAR (MAX)  NULL,
    [Is_Manual_ExtraCharges]  BIT             DEFAULT ((0)) NOT NULL,
    [TokenNumber]             NVARCHAR (100)  NULL,
    [user_id]                 INT             NULL,
    [discount_percent]        DECIMAL (18, 2) DEFAULT ((0)) NOT NULL,
    [no_of_bill]              INT             DEFAULT ((0)) NOT NULL,
    [is_deleted_print]        INT             NULL,
    [credit_card_no]          NVARCHAR (50)   NULL,
    [account_title]           NVARCHAR (50)   NULL,
    [tab_unique_id]           NVARCHAR (50)   NULL,
    [unique_key]              VARCHAR (50)    NULL,
    [advance_amount]          DECIMAL (18, 2) DEFAULT ((0)) NULL,
    [deliver_time]            DATETIME        NULL,
    [dispatch_time]           DATETIME        NULL,
    [duration]                VARCHAR (20)    NULL,
    [is_table_transfer]       BIT             DEFAULT ((0)) NULL,
    [android_device_no]       NVARCHAR (50)   NULL,
    [new_order_no]            NVARCHAR (50)   NULL,
    [kds_done]                BIT             DEFAULT ((0)) NULL,
    [luckyDraw]               INT             DEFAULT ((0)) NULL,
    [online_order_id]         INT             DEFAULT ((0)) NULL,
    [commission]              FLOAT (53)      NULL,
    [ctfp]                    BIT             DEFAULT ((0)) NULL,
    [ctfp_date]               DATETIME        NULL,
    [order_map_commission_id] INT             DEFAULT ((0)) NULL,
    [voucherno]               VARCHAR (20)    NULL,
    [onlineinvoicenumber]     VARCHAR (20)    NULL,
    [cashback]                FLOAT (53)      NULL,
    [VoucherAmount]           FLOAT (53)      NULL,
    [is_delete_fp]            BIT             DEFAULT ((0)) NULL
);

