CREATE TABLE [dbo].[ItemPOS] (
    [id]                INT             IDENTITY (1, 1) NOT NULL,
    [category_name]     NVARCHAR (50)   NULL,
    [item_name]         NVARCHAR (250)  NULL,
    [cost_price]        FLOAT (53)      NULL,
    [sale_price]        FLOAT (53)      NULL,
    [codes]             NVARCHAR (250)  NULL,
    [status]            BIT             CONSTRAINT [DF_Item_status] DEFAULT ((1)) NOT NULL,
    [tiltId]            INT             NULL,
    [IsComment]         BIT             CONSTRAINT [DF_ItemPOS_IsComment] DEFAULT ((0)) NULL,
    [orderid]           INT             DEFAULT ((0)) NOT NULL,
    [GetType]           NVARCHAR (50)   NULL,
    [Is_Open]           BIT             DEFAULT ((0)) NOT NULL,
    [Unit]              NVARCHAR (50)   NULL,
    [ItemParLevel]      DECIMAL (18, 2) DEFAULT ((0)) NOT NULL,
    [ItemBalance]       DECIMAL (18, 2) DEFAULT ((0)) NOT NULL,
    [item_name_arabic]  NVARCHAR (MAX)  NULL,
    [IsDate_Effective]  BIT             DEFAULT ((0)) NOT NULL,
    [FromDate]          DATETIME        NULL,
    [ToDate]            DATETIME        NULL,
    [ByeOneGetOneFree]  BIT             DEFAULT ((0)) NOT NULL,
    [FinalQty]          DECIMAL (18)    DEFAULT ((0)) NOT NULL,
    [Is_AutoPunchItem]  BIT             DEFAULT ((0)) NOT NULL,
    [AutoPunchItem_Id]  INT             DEFAULT ((0)) NOT NULL,
    [ExtraItem]         BIT             DEFAULT ((0)) NOT NULL,
    [Item_Commission]   DECIMAL (18, 2) DEFAULT ((0)) NOT NULL,
    [is_delete]         BIT             DEFAULT ((0)) NULL,
    [is_feedback]       BIT             DEFAULT ((0)) NULL,
    [image_url]         NVARCHAR (MAX)  NULL,
    [Is_upload]         BIT             DEFAULT ((0)) NOT NULL,
    [Is_update]         BIT             DEFAULT ((0)) NOT NULL,
    [is_charity]        BIT             DEFAULT ((0)) NULL,
    [charity_amount]    DECIMAL (18, 2) DEFAULT ((0)) NULL,
    [meal_type_id]      INT             DEFAULT ((0)) NULL,
    [discount_apply]    BIT             DEFAULT ((0)) NULL,
    [item_name_chinese] NVARCHAR (50)   NULL,
    [item_name_urdu]    NVARCHAR (50)   NULL,
    [is_kot]            BIT             DEFAULT ((0)) NULL
);

