CREATE TABLE [dbo].[Order_Payment] (
    [id]                      INT             IDENTITY (1, 1) NOT NULL,
    [order_key]               NVARCHAR (50)   NOT NULL,
    [date]                    DATETIME        NULL,
    [z_number]                NVARCHAR (50)   NULL,
    [order_type]              NVARCHAR (50)   NULL,
    [cash_sale]               FLOAT (53)      NULL,
    [credit_sale]             FLOAT (53)      NULL,
    [sub_total]               FLOAT (53)      NULL,
    [discount]                FLOAT (53)      NULL,
    [tax]                     FLOAT (53)      NULL,
    [net_sale]                FLOAT (53)      NULL,
    [net_bill]                FLOAT (53)      NULL,
    [is_delete]               BIT             CONSTRAINT [DF_Order_Payment_is_delete] DEFAULT ((0)) NULL,
    [ent]                     FLOAT (53)      NULL,
    [Tiltid]                  INT             NULL,
    [CounterId]               INT             NULL,
    [ServiceCharges]          DECIMAL (18, 2) DEFAULT ((0)) NULL,
    [Tip]                     DECIMAL (18, 2) DEFAULT ((0)) NULL,
    [ExtraCharges]            DECIMAL (18, 2) CONSTRAINT [DF_Order_Payment_ExtraCharges] DEFAULT ((0)) NULL,
    [CreditCardNo]            NVARCHAR (50)   NULL,
    [Status]                  BIT             DEFAULT ((0)) NOT NULL,
    [AdvanceBookingCode]      NVARCHAR (50)   NULL,
    [Description]             NVARCHAR (50)   NULL,
    [Advance]                 DECIMAL (18, 2) DEFAULT ((0)) NOT NULL,
    [VoucherAmount]           DECIMAL (18, 2) DEFAULT ((0)) NULL,
    [VoucherQty]              FLOAT (53)      DEFAULT ((0)) NULL,
    [is_upload]               BIT             DEFAULT ((0)) NOT NULL,
    [is_update]               BIT             DEFAULT ((0)) NOT NULL,
    [bank]                    NVARCHAR (50)   NULL,
    [time]                    NVARCHAR (50)   NULL,
    [Date_time]               DATETIME        NULL,
    [ItemComplimentry_Amount] DECIMAL (18, 2) DEFAULT ((0)) NOT NULL,
    [account_title]           NVARCHAR (100)  NULL,
    [transaction_code]        NVARCHAR (20)   NULL,
    [unique_key]              VARCHAR (50)    NULL
);

