CREATE TABLE [dbo].[Order_Detail] (
    [id]                      INT             IDENTITY (1, 1) NOT NULL,
    [order_key]               NVARCHAR (50)   NULL,
    [date]                    DATETIME        NULL,
    [z_number]                NVARCHAR (50)   NULL,
    [category_name]           NVARCHAR (50)   NULL,
    [item_name]               NVARCHAR (50)   NULL,
    [qty]                     FLOAT (53)      NULL,
    [price]                   FLOAT (53)      NULL,
    [tiltId]                  INT             NULL,
    [CounterId]               INT             NULL,
    [Discount]                DECIMAL (18, 2) CONSTRAINT [DF_Order_Detail_Discount] DEFAULT ((0)) NULL,
    [PriceBeforeDiscount]     DECIMAL (18, 2) CONSTRAINT [DF_Order_Detail_PriceBeforeDiscount] DEFAULT ((0)) NULL,
    [Status]                  BIT             CONSTRAINT [DF_Order_Detail_Status] DEFAULT ((0)) NULL,
    [OrderKey_Merege]         NVARCHAR (50)   NULL,
    [is_upload]               BIT             DEFAULT ((0)) NOT NULL,
    [is_update]               BIT             DEFAULT ((0)) NOT NULL,
    [ItemId]                  INT             DEFAULT ((0)) NOT NULL,
    [Is_Open]                 BIT             DEFAULT ((0)) NOT NULL,
    [Unit]                    NVARCHAR (50)   NULL,
    [Is_Served]               BIT             DEFAULT ((0)) NOT NULL,
    [IsCommplimentary]        BIT             DEFAULT ((0)) NOT NULL,
    [Commplimentary_Id]       NVARCHAR (50)   NULL,
    [Free]                    BIT             DEFAULT ((0)) NOT NULL,
    [ItemComplimentry_Amount] DECIMAL (18, 2) DEFAULT ((0)) NOT NULL,
    [Comments]                NVARCHAR (MAX)  NULL,
    [Is_IsComments]           BIT             DEFAULT ((0)) NULL,
    [Is_AutoPunchItem]        BIT             DEFAULT ((0)) NOT NULL,
    [parent_Id]               INT             DEFAULT ((0)) NOT NULL,
    [tax]                     DECIMAL (18, 2) DEFAULT ((0)) NOT NULL,
    [android_detail_id]       INT             DEFAULT ((0)) NULL,
    [unique_key]              VARCHAR (50)    NULL,
    [is_additional]           BIT             DEFAULT ((0)) NULL,
    [is_paid]                 BIT             DEFAULT ((0)) NULL,
    [start_time]              DATETIME        NULL,
    [end_time]                DATETIME        NULL,
    [duration]                VARCHAR (50)    NULL,
    [cashback]                FLOAT (53)      NULL
);

