CREATE TABLE [dbo].[ShiftAmount] (
    [id]            INT             IDENTITY (1, 1) NOT NULL,
    [TiltId]        INT             NULL,
    [Z_Number]      NVARCHAR (50)   NULL,
    [OpeningAmount] DECIMAL (18, 2) NULL,
    [ClosingAmount] DECIMAL (18, 2) NULL,
    [TimeIn]        NVARCHAR (50)   NULL,
    [TimeOut]       NVARCHAR (50)   NULL,
    [IsActive]      BIT             CONSTRAINT [DF_ShiftAmount_IsActive] DEFAULT ((0)) NULL,
    [OpeningDate]   DATETIME        NULL,
    [ClosingDate]   DATETIME        NULL,
    [OpenedBy]      NVARCHAR (50)   NULL,
    [ClosedBy]      NVARCHAR (50)   NULL,
    [Ten]           NVARCHAR (50)   NULL,
    [Twenty]        NVARCHAR (50)   NULL,
    [Fifty]         NVARCHAR (50)   NULL,
    [Hundred]       NVARCHAR (50)   NULL,
    [FiveHundred]   NVARCHAR (50)   NULL,
    [Thousands]     NVARCHAR (50)   NULL,
    [FiveThousands] NVARCHAR (50)   NULL,
    [TenThousands]  NVARCHAR (50)   NULL,
    [One]           NVARCHAR (50)   DEFAULT ((0)) NOT NULL,
    [Two]           NVARCHAR (50)   DEFAULT ((0)) NOT NULL,
    [five]          NVARCHAR (50)   DEFAULT ((0)) NOT NULL,
    [is_upload]     BIT             DEFAULT ((0)) NOT NULL,
    [is_update]     BIT             DEFAULT ((0)) NOT NULL,
    [id_]           INT             DEFAULT ((0)) NOT NULL
);

