CREATE TABLE [dbo].[tbl_user] (
    [id]                          INT           IDENTITY (1, 1) NOT NULL,
    [username]                    NVARCHAR (50) NULL,
    [pwd]                         NVARCHAR (50) NULL,
    [adminsetting]                BIT           NULL,
    [inventory_setting]           BIT           CONSTRAINT [DF_tbl_user_inventory_setting] DEFAULT ((0)) NULL,
    [create_change_user]          BIT           NULL,
    [create_change_shift]         BIT           NULL,
    [point_of_sale]               BIT           NULL,
    [sales_reports]               BIT           CONSTRAINT [DF_tbl_user_sales_reports] DEFAULT ((0)) NULL,
    [item_less]                   BIT           CONSTRAINT [DF_tbl_user_item_less] DEFAULT ((0)) NULL,
    [discount]                    BIT           CONSTRAINT [DF_tbl_user_discount] DEFAULT ((0)) NULL,
    [order_delete]                BIT           CONSTRAINT [DF_tbl_user_order_delete] DEFAULT ((0)) NULL,
    [ent]                         BIT           CONSTRAINT [DF_tbl_user_ent] DEFAULT ((0)) NULL,
    [RptMenu]                     BIT           CONSTRAINT [DF_tbl_user_RptMenu] DEFAULT ((0)) NULL,
    [RptShiftWiseFinancial]       BIT           CONSTRAINT [DF_tbl_user_RptShiftWiseFinancial] DEFAULT ((0)) NULL,
    [RptXReportsFinancial]        BIT           CONSTRAINT [DF_tbl_user_RptXReportsFinancial] DEFAULT ((0)) NULL,
    [RptXReportsCategory]         BIT           CONSTRAINT [DF_tbl_user_RptXReportsCategory] DEFAULT ((0)) NULL,
    [RptXReportsItem]             BIT           CONSTRAINT [DF_tbl_user_RptXReportsItem] DEFAULT ((0)) NULL,
    [RptRunningTables]            BIT           CONSTRAINT [DF_tbl_user_RptRunningTables] DEFAULT ((0)) NULL,
    [RptTakeAwayCustomer]         BIT           CONSTRAINT [DF_tbl_user_RptTakeAwayCustomer] DEFAULT ((0)) NULL,
    [RptDeliveryCustomer]         BIT           CONSTRAINT [DF_tbl_user_RptDeliveryCustomer] DEFAULT ((0)) NULL,
    [RptDistributedReport]        BIT           CONSTRAINT [DF_tbl_user_RptDistributedReport] DEFAULT ((0)) NULL,
    [RptItem]                     BIT           CONSTRAINT [DF_tbl_user_RptItem] DEFAULT ((0)) NULL,
    [RptFinancial]                BIT           CONSTRAINT [DF_tbl_user_RptFinancial] DEFAULT ((0)) NULL,
    [RptCategory]                 BIT           CONSTRAINT [DF_tbl_user_RptCategory] DEFAULT ((0)) NULL,
    [RptCovers]                   BIT           CONSTRAINT [DF_tbl_user_RptCovers] DEFAULT ((0)) NULL,
    [RptOrderDetails]             BIT           CONSTRAINT [DF_tbl_user_RptOrderDetails] DEFAULT ((0)) NULL,
    [RptDiscount]                 BIT           CONSTRAINT [DF_tbl_user_RptDiscount] DEFAULT ((0)) NULL,
    [RptEnt]                      BIT           CONSTRAINT [DF_tbl_user_RptEnt] DEFAULT ((0)) NULL,
    [RptOrderDelete]              BIT           CONSTRAINT [DF_tbl_user_RptOrderDelete] DEFAULT ((0)) NULL,
    [RptItemLess]                 BIT           CONSTRAINT [DF_tbl_user_RptItemLess] DEFAULT ((0)) NULL,
    [RptDeliveryOrders]           BIT           CONSTRAINT [DF_tbl_user_RptDeliveryOrders] DEFAULT ((0)) NULL,
    [RptBillHistory]              BIT           CONSTRAINT [DF_tbl_user_RptBillHistory] DEFAULT ((0)) NULL,
    [RptWaiterPerformance]        BIT           CONSTRAINT [DF_tbl_user_RptWaiterPerformance] DEFAULT ((0)) NULL,
    [RptCategoryByDepart]         BIT           CONSTRAINT [DF_tbl_user_RptCategoryByDepart] DEFAULT ((0)) NULL,
    [OpeningAmount]               BIT           CONSTRAINT [DF_tbl_user_OpeningAmount] DEFAULT ((0)) NULL,
    [ClosingAmount]               BIT           CONSTRAINT [DF_tbl_user_ClosingAmount] DEFAULT ((0)) NULL,
    [CashDrop]                    BIT           CONSTRAINT [DF_tbl_user_CashDrop] DEFAULT ((0)) NULL,
    [IsCash]                      BIT           CONSTRAINT [DF_tbl_user_IsCash] DEFAULT ((0)) NULL,
    [LoginStatus]                 BIT           CONSTRAINT [DF_tbl_user_LoginStatus] DEFAULT ((0)) NULL,
    [UserWiseOrder]               BIT           CONSTRAINT [DF_tbl_user_UserWiseOrder] DEFAULT ((0)) NULL,
    [InventoryFunctional]         BIT           CONSTRAINT [DF_tbl_user_InventoryFunctional] DEFAULT ((0)) NULL,
    [InventorySettings]           BIT           CONSTRAINT [DF_tbl_user_InventorySettings] DEFAULT ((0)) NULL,
    [InventoryReports]            BIT           CONSTRAINT [DF_tbl_user_InventoryReports] DEFAULT ((0)) NULL,
    [AccountsFunctional]          BIT           CONSTRAINT [DF_tbl_user_AccountsFunctional] DEFAULT ((0)) NULL,
    [AccountsSettings]            BIT           CONSTRAINT [DF_tbl_user_AccountsSettings] DEFAULT ((0)) NULL,
    [AccountsReports]             BIT           CONSTRAINT [DF_tbl_user_AccountsReports] DEFAULT ((0)) NULL,
    [CreateUser]                  BIT           DEFAULT ((0)) NOT NULL,
    [Tiltid]                      INT           DEFAULT ((0)) NOT NULL,
    [CardData]                    NVARCHAR (50) NULL,
    [ReportsPOS]                  BIT           DEFAULT ((1)) NOT NULL,
    [is_upload]                   BIT           DEFAULT ((0)) NOT NULL,
    [is_update]                   BIT           DEFAULT ((0)) NOT NULL,
    [N_AdvBooking]                BIT           DEFAULT ((0)) NOT NULL,
    [N_All_Orders]                BIT           DEFAULT ((0)) NOT NULL,
    [n_CashDrop]                  BIT           DEFAULT ((0)) NOT NULL,
    [N_CreditSale]                BIT           DEFAULT ((0)) NOT NULL,
    [N_DeptWise_Sale]             BIT           DEFAULT ((0)) NOT NULL,
    [N_Financial_Running_Shift]   BIT           DEFAULT ((0)) NOT NULL,
    [N_Item_Running_Shift]        BIT           DEFAULT ((0)) NOT NULL,
    [N_Item_Zero]                 BIT           DEFAULT ((0)) NOT NULL,
    [N_ItemRate]                  BIT           DEFAULT ((0)) NOT NULL,
    [N_Ledger]                    BIT           DEFAULT ((0)) NOT NULL,
    [N_LoginStatus]               BIT           DEFAULT ((0)) NOT NULL,
    [N_RiderCashFloat]            BIT           DEFAULT ((0)) NOT NULL,
    [N_RiderPerformance]          BIT           DEFAULT ((0)) NOT NULL,
    [N_SaleDetail]                BIT           DEFAULT ((0)) NOT NULL,
    [N_SaleReturn]                BIT           DEFAULT ((0)) NOT NULL,
    [N_shift_Counter_Report]      BIT           DEFAULT ((0)) NOT NULL,
    [N_Table_Running_Shift]       BIT           DEFAULT ((0)) NOT NULL,
    [N_Table_Summary]             BIT           DEFAULT ((0)) NOT NULL,
    [N_table_time]                BIT           DEFAULT ((0)) NOT NULL,
    [N_TakeAwayOrders]            BIT           DEFAULT ((0)) NOT NULL,
    [n_Tax]                       BIT           DEFAULT ((0)) NOT NULL,
    [N_TopSale_Item]              BIT           DEFAULT ((0)) NOT NULL,
    [N_TopSale_Item_CategoryWise] BIT           DEFAULT ((0)) NOT NULL,
    [ItemTransfer]                BIT           DEFAULT ((0)) NOT NULL,
    [OrderTransfer]               BIT           DEFAULT ((0)) NOT NULL,
    [DuplicateKOT]                BIT           DEFAULT ((0)) NOT NULL,
    [ItemComplimentry]            BIT           DEFAULT ((0)) NOT NULL,
    [PartyAccount]                BIT           DEFAULT ((0)) NOT NULL,
    [SaleView]                    BIT           DEFAULT ((0)) NOT NULL,
    [IsDeliveryCharges]           BIT           DEFAULT ((0)) NOT NULL,
    [order_delete_after_bill]     BIT           DEFAULT ((0)) NULL,
    [item_less_after_bill]        BIT           DEFAULT ((0)) NULL,
    [only_bill]                   BIT           DEFAULT ((0)) NOT NULL,
    [user_wise_order]             BIT           DEFAULT ((0)) NOT NULL,
    [dine_in]                     BIT           DEFAULT ((0)) NULL,
    [takeaway]                    BIT           DEFAULT ((0)) NULL,
    [delivery]                    BIT           DEFAULT ((0)) NULL,
    CONSTRAINT [PK_tbl_user] PRIMARY KEY CLUSTERED ([id] ASC)
);

