CREATE TABLE [dbo].[tempDine_In_Order] (
    [id]               INT             IDENTITY (1, 1) NOT NULL,
    [order_key]        NVARCHAR (50)   NOT NULL,
    [z_number]         NVARCHAR (50)   NULL,
    [order_type]       NVARCHAR (50)   NULL,
    [order_no]         INT             NULL,
    [order_date]       DATETIME        NULL,
    [day]              NVARCHAR (50)   NULL,
    [table_no]         NVARCHAR (50)   NULL,
    [waiter_name]      NVARCHAR (50)   NULL,
    [order_time]       NVARCHAR (50)   NULL,
    [service_time]     NVARCHAR (50)   NULL,
    [service_status]   NVARCHAR (50)   NULL,
    [account_status]   NVARCHAR (50)   NULL,
    [amount]           FLOAT (53)      NULL,
    [DiscountType]     NVARCHAR (50)   NULL,
    [discount]         DECIMAL (18)    CONSTRAINT [DF_tempDine_In_Order_discount] DEFAULT ((0)) NULL,
    [is_delete]        BIT             CONSTRAINT [DF_tempDine_In_Order_is_delete] DEFAULT ((0)) NULL,
    [cover]            DECIMAL (18)    CONSTRAINT [DF_tempDine_In_Order_cover] DEFAULT ('0') NOT NULL,
    [estimated_time]   NVARCHAR (50)   NULL,
    [table_time]       NVARCHAR (50)   NULL,
    [kitchen_status]   BIT             CONSTRAINT [DF_tempDine_In_Order_kitchen_status] DEFAULT ((0)) NOT NULL,
    [Tiltid]           INT             NULL,
    [CounterId]        INT             NULL,
    [IsBill]           BIT             CONSTRAINT [DF_tempDine_In_Order_IsBill] DEFAULT ((0)) NULL,
    [CareOff]          NVARCHAR (100)  NULL,
    [IsSelect]         BIT             CONSTRAINT [DF_tempDine_In_Order_IsSelect] DEFAULT ((0)) NULL,
    [Customer]         NVARCHAR (MAX)  NULL,
    [Tele]             NVARCHAR (50)   NULL,
    [ExtraCharges]     DECIMAL (18, 2) CONSTRAINT [DF_tempDine_In_Order_ExtraCharges] DEFAULT ((0)) NULL,
    [DeleteReason]     NVARCHAR (MAX)  NULL,
    [UserPunch]        NVARCHAR (MAX)  NULL,
    [UserCash]         NVARCHAR (MAX)  NULL,
    [UserDelete]       NVARCHAR (MAX)  NULL,
    [KOT]              INT             CONSTRAINT [DF_tempDine_In_Order_KOT] DEFAULT ((0)) NULL,
    [tableStatus]      BIT             CONSTRAINT [DF_tempDine_In_Order_tableStatus] DEFAULT ((0)) NULL,
    [OrderTiltId]      INT             CONSTRAINT [DF_tempDine_In_Order_OrderTiltId] DEFAULT ((0)) NULL,
    [TimeIn]           DATETIME        NULL,
    [TimeOut]          DATETIME        NULL,
    [Status]           BIT             DEFAULT ((0)) NOT NULL,
    [Od]               INT             DEFAULT ((0)) NOT NULL,
    [Itemqty]          FLOAT (53)      DEFAULT ((0)) NOT NULL,
    [Itemprice]        FLOAT (53)      DEFAULT ((0)) NOT NULL,
    [OrderKey_Merege]  NVARCHAR (50)   NULL,
    [DispatchTime]     NVARCHAR (50)   NULL,
    [OrderStatus]      NVARCHAR (50)   NULL,
    [PaymentMode]      NVARCHAR (50)   NULL,
    [isFeedback]       BIT             DEFAULT ((0)) NOT NULL,
    [Feedback]         NVARCHAR (MAX)  NULL,
    [DiscountId]       NVARCHAR (50)   NULL,
    [voucherno]        VARCHAR (20)    NULL,
    [VoucherAmount]    FLOAT (53)      NULL,
    [discount_percent] DECIMAL (18, 2) DEFAULT ((0)) NULL
);

